### ISSUE TITLE
Tabs in dropdown menu get "compounded" to single tab

### ISSUE THREAD

**Issue by pastapojken** [jneilliii/OctoPrint-DragonOrder#11]
Hi!

Basically, dragging to re-order works, but all the tabs in the "dropdown menu" on the right get all put together into one. The ```#tab_plugin``` url stuff changes but nothing happens unless i click on the first item of the dropdown menu (when I took this screenshots it was the "hardwarePWM" plugin). I've no clue how to fix this, uninstalling or re-ordering (both in the plugin or in ```config.yaml```) doesn't work, any idea how to fix this?

Images of the issue are [here](https://imgur.com/a/Jd65k3C), last image is how (for example) "hardwarePWM" should look.

Thanks!

**Comment by jneilliii** [comment]
This may be a plugin conflict. Does it do the same if octolapse or hardwarepwm is disabled?

**Comment by pastapojken** [comment]
Oh wow found the issue, had missed a ```</div>``` in the ```jinja2``` nav file, sorry!
