### ISSUE TITLE
Move all headers around and make new column

### ISSUE THREAD

**Issue by Beeblebrox666** [jneilliii/OctoPrint-DragonOrder#12]
Can you make you plugin do this?
![Octoprint Modified](https://user-images.githubusercontent.com/29876058/61597617-bc331880-abe0-11e9-82b3-44d304ab1b59.jpg)

**Comment by jneilliii** [comment]
Potentially by adding another side panel, but not sure if that would interfere with some of the data binding to the widgets or not.

**Comment by jneilliii** [comment]
Created separate plugin for this use case as described in the community forum thread you started.
