### ISSUE TITLE
Shift holding issue with TouchUI

### ISSUE THREAD

**Issue by buzkill420** [jneilliii/OctoPrint-DragonOrder#14]
Love your addon and use it to actually fix a bug with touchUI BUT that being said It is impossible to refresh and close the warning pop up dragon creates and kinda defeats the whole point of using it....

any way you could incorporate an X box to close the warning on a touchscreen?

Thank you! @jneilliii

**Comment by jneilliii** [comment]
New release that should show the close button on the pop up when touchui is enabled and active.
