### ISSUE TITLE
incompatibility with Custom Control Editor

### ISSUE THREAD

**Issue by kb-** [jneilliii/OctoPrint-DragonOrder#17]
I just reactivated DragonOrder and updated it to v0.1.5. 
Right after dragging the GCode Viewer tab next to the control tab, I noticed all of my custom controls, created with "Custom Control Editor" disappeared! The settings all got deleted.

"System Command Editor"'s settings got deleted as well.

Octoprint 1.4.2
OctoPi Version 0.15.1, running on Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by jneilliii** [comment]
This is actually a bug with both those plugins and the way that it saves those settings. There are issues posted on each of their repos already about it and I submitted a PR to Custom Controls on a quick fix, but it has not been merged.
