### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Doprintityourself** [jneilliii/OctoPrint-DragonOrder#18]
I installed Drag on Order but I dont get a clue how to use it 
A bit more precise information about how to use would be very helpful
Best would be a movie on youtube or elseware.
Either cannot drag tabs or from the sidevbar
disabled Themeify or wide screen 
but no way to get anything moved

Thanks in advance

**Comment by jneilliii** [comment]
Hopefully this helps.

https://youtu.be/IxcpjgPiytQ
