### ISSUE TITLE
does not save my layout modification

### ISSUE THREAD

**Issue by robomaniac** [jneilliii/OctoPrint-DragonOrder#2]
I like this idea. I move all the windows like I want but when I open octoprint via chrome I have to start over.
It does not save the way I have place the windows.

also when I open my octoprint with iOS device in chrome, all those layout modification are not there.
That is the main reason I wanted this to work on my phone since it's a small screen, I wanted a different layout.

**Comment by robomaniac** [comment]
I unplug my pi for other reason and it booted with my custom settings. So it works. And it works on iOS!

Thanks

**Comment by jneilliii** [comment]
Yeah, probably just needed a force reload.
