### ISSUE TITLE
after uninstalled plugin, the order keep same

### ISSUE THREAD

**Issue by plyn-algo** [jneilliii/OctoPrint-DragonOrder#20]
Hi, 
I have a small problem here.
I am running: OctoPrint 1.6.1  Python 3.7.3  OctoPi 0.17.0
I used to have Dragon Order plugin installed, but because I often misclicked and disordered the widgets, bars etc.. I decided to uninstall the plugin and use Tab order plugin, which is perfect for me.
I uninstalled the Dragon order plugin via plugin manager and choosed "uninstall & clean up plugin data" option.
After restart, the plugin disapeared but the order of Tabs (and also widgets) kept same and I am not able to organize it by Tab order Plugin (I am able to organize tabs, which wasn't moved before). I tried to install and uninstall the plugin once again, but with no result.
I know, that I can install the plugin, organize the tabs as I'd like to and than disable the plugin. But I don't want to do it every time I'd like to swap only one tab.
Interestig thing is, that the order keep same (not original) also after restart in safe mode.

So, not sure, if it's really bug or if the plugin actually directlly change the octoprints UI.
Also not sure, if only me has this problem.

If it is possible to make some small and easy bug-fix release, it would be very nice. Or can I manually uninstall some "remaining plugin data" or do some another easy fix? 

If not, making octoprint backup, reinstalling whole octoprint and reloading backup should help me, shouldn't it?
(But the disorder is actually better than do the installation again 🤣 😞 )

In every case, thank you very very much for your help!

**Comment by jneilliii** [comment]
This is actually intended because the plugin is changing default settings in config.yaml that can be done manually as well. To go back to default sorting order you would have to edit config.yaml and remove the appearance > order section. Not sure if there is a way to do that on uninstall, but it's something that might not be expected. Here are the steps to get back to default.

SSH to the pi
```
nano ~/.octoprint/config.yaml
```
find the appearance section using the arrows on your keyboard and delete the order section. press ctrl+x, answer yes to the prompt and then press enter to keep the same file name.
```
sudo service octoprint restart
```
should be back to default.

**Comment by plyn-algo** [comment]
Thank you very much, it helped! but now I am not able to sort it with tab order plugin.

**Comment by jneilliii** [comment]
Are there any errors in octoprint.log or the browser's developer tools (F12) on the console tab during page load? If you hold down shift and refresh does that make any difference?

**Comment by plyn-algo** [comment]
in octoprint.log i found only this:
2021-07-24 21:22:46,996 - octoprint.plugins.TimeToFilament - ERROR - Failed: AttributeError("'NoneType' object has no attribute '_currentFile'")

And in browser console only this:
Source map error: Error: request failed with status 404
URL adress source: http://octopi.local/plugin/toptemp/static/js/chartist-plugin-axistitle.min.js
URL adress source map: chartist-plugin-axistitle.min.js.map

Maybe this errors are only because my printer is disconected right now.

**Comment by plyn-algo** [comment]
I tried it again with connected printer and I didn't find any errors in octoprint.log
but the second error stay same.
And if I hold down shift and refresh I don't observe any diference.

**Comment by jneilliii** [comment]
interesting. can you try to make a change in tab order and save and see if it does anything, or is that what you were already trying?

**Comment by plyn-algo** [comment]
yes, I have tried that many times... and with no result, everything keep same - default.

**Comment by jneilliii** [comment]
Please open issue on that plugin's repo.
