### ISSUE TITLE
How to save changes??

### ISSUE THREAD

**Issue by mirzaMk90** [jneilliii/OctoPrint-DragonOrder#25]
Hi,
I have problem because when I drag some element in UI it won't stay there after refresh page or when I next time open UI.

I'm trying to reorder left column of the UI page.
I have "MACRO" element which originally was on bottom and I drag them up. In first they won't stay up there but after some time, I don't know how, they stay up.
Now I have the same issue with "FIlament Manager" element.
After every refresh the element drops on to bottom.

![image](https://user-images.githubusercontent.com/119226287/217518479-97167558-e264-4cd8-ae67-f288a8bb3f2b.png)

**Comment by mirzaMk90** [comment]
Well..the problem is solved after rebooting raspberry Pi.
I try restart just octoprint service and nothing. After reboot hole raspberry it worked...

**Comment by jneilliii** [comment]
Normally presenting the save button is enough, but sometimes you have to force a refresh in your browser. Glad you got it worked out.
