### ISSUE TITLE
tried to select text but start dragging windows

### ISSUE THREAD

**Issue by robomaniac** [jneilliii/OctoPrint-DragonOrder#3]
I tried to copy paste an error msg in my connection section. Instead of selecting the text it started dragging the window. It's impossible to select text. Do you think that you could start dragging only when top portion is selected? 

when was the last time I tried to copy text from those windows? never. Maybe not a big deal.
it's just something I notice.

(using chrome, win7)

**Comment by jneilliii** [comment]
This should be fixed in the latest 0.1.2 version.  I limited the sidebar dragging to the header row of the sidebar panels.
