### ISSUE TITLE
Refresh browser doesn't keep settings

### ISSUE THREAD

**Issue by Texy** [jneilliii/OctoPrint-DragonOrder#4]
I can drag the tabs from the default settings, and the 'extra' tabs, previously in the pull down menu expand as they should. A pop up window then tells me to hold shift and refresh page. This bit doesn't work for me - it goes back to the pre-expanded view. Using Windows 10 and Edge.
Texy

**Comment by jneilliii** [comment]
I just tested the following in Windows 10 on Edge and it seems to work.  Hold down the ctrl key on your keyboard and press the F5 key.

**Comment by OutsourcedGuru** [comment]
macOS Mojave 10.14.1
Safari 12.0.1
Themeify (personal fork)

The drag/drop appears to work at first, yielding the expected notification.

![screen shot 2018-11-23 at 3 25 21 pm](https://user-images.githubusercontent.com/15971213/48962375-0a015f00-ef34-11e8-89bf-70c1bc98b82e.png)

Unfortunately, it doesn't feel like adding the Shift key to the standard Cmd+R reload combination is doing anything. On the Mac, an Opt+Cmd+E clears the cache and following this with a standard Cmd+R just reverts back to the original ordering.

Subset of `~/.octoprint/config.yaml` after the drag/drop:
```
appearance:
  components:
    order:
      tab:
      - temperature
      - control
      - terminal
      - timelapse
      - gcodeviewer
```

## Workaround
I do a restart from the System menu and the tabs are in the new order. Another page reload dismisses the notification.

![screen shot 2018-11-23 at 3 30 18 pm](https://user-images.githubusercontent.com/15971213/48962427-ba6f6300-ef34-11e8-9cef-fcfeea0f4ff9.png)

**Comment by jneilliii** [comment]
@OutsourcedGuru, what about if you hold the Option key and press the Reload button in the safari toolbar?

**Comment by Texy** [comment]
>           I just tested the following in Windows 10 on Edge and it seems to work.  Hold down the ctrl key on your keyboard and press the F5 key.

This almost works. It keeps the rearranged tab order, but it still collapses the pull down menu items.
Texy

**Comment by jneilliii** [comment]
Yeah it might be. I'll have to search through octoprint code to see if there is a way to force a cache reload. I asked in the community forum before but never got a solid answer.

**Comment by OutsourcedGuru** [comment]
I just created a `save` subfolder under `webassets` and moved all that into it. Option-reloading showed me a raw page without any styling and the tab order was the original. So I think you can rule out webassets as the culprit.

**Comment by OutsourcedGuru** [comment]
Looks like it's the core [Viewmodel](https://github.com/foosel/OctoPrint/blob/97d37c50787a6915cc61e0d0158ea98c7648bd1a/src/octoprint/server/views.py) itself with "entry_order". Sounds like a restart of OctoPrint to me or figure out some way of bumping the Viewmodel to reset.

**Comment by TheKrush** [comment]
For chrome it's not [shift] it's [ctrl] to force a reload that loads up the order correctly.
