### ISSUE TITLE
Error when installing. "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by MrJabu** [jneilliii/OctoPrint-DragonOrder#7]
I am getting an error when trying to install it.

i run sudo pip install "https://github.com/jneilliii/OctoPrint-DragonOrder/archive/master.zip"

and get

Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-I5QOlU/

i am on the latest build of octoprint.

**Comment by jneilliii** [comment]
What about installing from the plugin manager? That insures the proper pip is used. Otherwise, you need to make sure you're in the right location for running the command. For octopi that is in ~/oprint/bin/

**Comment by MrJabu** [comment]
i tried in ~/oprint/bin/ too and same error.

i can not find it in the plugin manager. it doesnt show up

**Comment by jneilliii** [comment]
That's odd, must be filtered out for you for some reason.  It's definitely in the repo. What version of OctoPrint are you running and on what OS?

https://plugins.octoprint.org/plugins/dragon_order/

**Comment by MrJabu** [comment]
1.3.10  on Win10

**Comment by jneilliii** [comment]
Strange, I developed the plugin in that configuration and had no issues with it showing up.  Try this.

- Open command prompt and go to your root octoprint folder (ie cd c:\OctoPrint\).  
- Activate OctoPrint by typing `venv\Scripts\activate.bat` 
- Install plugin using the command

```venv\Scripts\pip.exe install https://github.com/jneilliii/OctoPrint-DragonOrder/archive/master.zip```

**Comment by MrJabu** [comment]
sorry my bad i am running octopi on a pi zero

**Comment by jneilliii** [comment]
Then you should be able to install within plugin manager.  Open that and search for dragon.

![image](https://user-images.githubusercontent.com/5249455/51432890-581da080-1c0d-11e9-9965-2cd79250d6b8.png)

Click Install.

**Comment by MrJabu** [comment]
got it working. thanks!
