### ISSUE TITLE
Handles not appearing, cannot reorder anything

### ISSUE THREAD

**Issue by dwtaylor99** [jneilliii/OctoPrint-DragonOrder#8]
I'm not seeing any handles, nor can I reorder the tabs. In fact the plug-in seems to have no affect at all. I tried in Chrome and Firefox. I disabled TouchUI and CyborgTheme, but that didn't help.

Plug-ins of note:
Cyborg Theme 0.1.6
TouchUI 0.3.12

Versions:
DragonOrder 0.1.2
OctoPrint 1.3.10 running on OctoPi 0.13.0

**Comment by jneilliii** [comment]
Are there any errors in your browser's development console?

**Comment by dwtaylor99** [comment]
This error occurs when I click inside the "Connection", "State", or "Files" sections.

![dragon-order-error](https://user-images.githubusercontent.com/16144203/51854835-60eb3200-22f1-11e9-8e72-b941e7b10ec3.png)

**Comment by dwtaylor99** [comment]
Wait. Ignore this. It's working fine. I just misunderstood what this plug-in does. There is no issue.
