### ISSUE TITLE
Feature Request - Lock Placement Once Re-Ordered

### ISSUE THREAD

**Issue by klownius** [jneilliii/OctoPrint-DragonOrder#9]
It would be nice if there was a setting that locks/unlocks the ability to reorder the tabs once I have them the way I like them.  This prevents accidentally dragging a tab when I really only meant to click it.  Which I do a lot.  Call it a me problem, but it would be nice to have :)!  Thank you!

**Comment by jneilliii** [comment]
You could always just disable the plugin after you've arranged them the way you want. The getting will stay as it's saving the internal config to octoprint's core settings.

**Comment by klownius** [comment]
I can do that.  Thank you!

**Comment by CryptoCrab** [comment]
Thanks for the info, I end up accidentally dragging them constantly (and the message that pops up cannot be closed).

@jneilliii Perhaps an option to add a modifier key to the click action could be useful in the plugin option dialog, something like Shift+Click/Drag to reorder? Just a thought. Thanks for the great plugin!

**Comment by jneilliii** [comment]
Once you order everything you can disable/ turn off the plugin in plugin manager and the order will keep.
